version: "3.8"

services:
  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    networks:
      - app_net

  backend:
    build: ./backend
    container_name: backend
    restart: always
    networks:
      - app_net

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app_net

networks:
  app_net:
    driver: bridge