services:
  backend:
    build: ./backend
    container_name: backend
    networks:
      - appnet
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - PORT=3000

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
