AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFront distribution for Full Stack Application'

Parameters:
  OriginDomainName:
    Type: String
    Description: 'Domain name of your ALB or EC2 instance running the dockerized app'
    Default: 'your-alb-domain.us-east-1.elb.amazonaws.com'
  
  CertificateArn:
    Type: String
    Description: 'ARN of ACM certificate for HTTPS (optional)'
    Default: ''

Conditions:
  HasCertificate: !Not [!Equals [!Ref CertificateArn, '']]

Resources:
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: 'Full Stack App Distribution'
        DefaultRootObject: 'index.html'
        
        Origins:
          - DomainName: !Ref OriginDomainName
            Id: 'FullStackAppOrigin'
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: 'http-only'
              OriginSSLProtocols:
                - TLSv1.2
        
        DefaultCacheBehavior:
          TargetOriginId: 'FullStackAppOrigin'
          ViewerProtocolPolicy: 'redirect-to-https'
          CachePolicyId: '4135ea2d-6df8-44a3-9df3-4b5a84be39ad'  # CachingDisabled
          OriginRequestPolicyId: '88a5eaf4-2fd4-4709-b370-b4c650ea3fcf'  # CORS-S3Origin
          Compress: true
          
        CacheBehaviors:
          # API routes - no caching
          - PathPattern: '/api/*'
            TargetOriginId: 'FullStackAppOrigin'
            ViewerProtocolPolicy: 'redirect-to-https'
            CachePolicyId: '4135ea2d-6df8-44a3-9df3-4b5a84be39ad'  # CachingDisabled
            OriginRequestPolicyId: '88a5eaf4-2fd4-4709-b370-b4c650ea3fcf'  # CORS-S3Origin
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              - PUT
              - POST
              - PATCH
              - DELETE
            CachedMethods:
              - GET
              - HEAD
          
          # Static assets - cache for 1 year
          - PathPattern: '/assets/*'
            TargetOriginId: 'FullStackAppOrigin'
            ViewerProtocolPolicy: 'redirect-to-https'
            CachePolicyId: '658327ea-f89d-4fab-a63d-7e88639e58f6'  # CachingOptimized
            Compress: true
        
        ViewerCertificate:
          !If
            - HasCertificate
            - AcmCertificateArn: !Ref CertificateArn
              SslSupportMethod: 'sni-only'
              MinimumProtocolVersion: 'TLSv1.2_2021'
            - CloudFrontDefaultCertificate: true
        
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: '/index.html'
            ErrorCachingMinTTL: 300
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: '/index.html'
            ErrorCachingMinTTL: 300
        
        HttpVersion: 'http2'
        IPV6Enabled: true
        PriceClass: 'PriceClass_100'

Outputs:
  CloudFrontDomainName:
    Description: 'CloudFront Distribution Domain Name'
    Value: !GetAtt CloudFrontDistribution.DomainName
    Export:
      Name: !Sub '${AWS::StackName}-CloudFrontDomain'
  
  CloudFrontDistributionId:
    Description: 'CloudFront Distribution ID'
    Value: !Ref CloudFrontDistribution
    Export:
      Name: !Sub '${AWS::StackName}-CloudFrontDistributionId'
